The workflow I use for Nyari News is to set up all the text in an EMACS org file from which I then cut and paste into the layout. If you are in here helping me with the writing and have cloned my github repository then please edit this file and push to the repo as you work so I can see what you are doing. As a team develops I hope that we'll have others working on other areas and will not duplicate our efforts while still have GIT track all our changes. Thanks for your help. Here are the topic areas that we work on for each newsletter. Edit each section as needed.

* Intro page
** notes about the AGM
- we need the new committee members
- attendance
* Finance
- projects we are going to undertake this fiscal year
* Security
* Environment
- Neal to find and write-up an article as usual
*** the write-up this time could be about a trip? One of my Tsavo trips?
*** what other Environmental issue could we raise for NRWS time time around?
* Maintenance
- Neal still has the pics of the repair to the gate rail under barrier 3 that Manraj Matharu supplied. Perhaps an article on this could be produced if nothing comes through from members.
* ICT
- how about a write-up about on-line ed?
* Staff profile
- Karanja please suggest another staff member to profile and do what you did lasdt time getting me photos and a short bit of text. This time though just dump the photos into the repo (here) and I'll pull them myself.
* Member profile
- this was a flop last time. Perhaps we get rid of it altogether from future newsletters.
* Advertising
- confirm payment from Taipan Forex has been received.
* various filler pages like
** Gallery
 - don't have any more gallery photos in my possession. If you have any please dump them in here - in a directory of your own please, and I'll see what you've posted.
** Suggestions welcome
